In [1]:
import pandas as pd

df = pd.read_csv("../dataset/Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv")

print(df.head())

print(df.shape)

print(df.columns)

                                   Flow ID       Source IP   Source Port  \
0  192.168.10.5-104.16.207.165-54865-443-6  104.16.207.165           443
1    192.168.10.5-104.16.28.216-55054-80-6   104.16.28.216            80
2    192.168.10.5-104.16.28.216-55055-80-6   104.16.28.216            80
3  192.168.10.16-104.17.241.25-46236-443-6   104.17.241.25           443
4  192.168.10.5-104.19.196.102-54863-443-6  104.19.196.102           443

   Destination IP   Destination Port   Protocol      Timestamp  \
0    192.168.10.5              54865          6  7/7/2017 3:30
1    192.168.10.5              55054          6  7/7/2017 3:30
2    192.168.10.5              55055          6  7/7/2017 3:30
3   192.168.10.16              46236          6  7/7/2017 3:30
4    192.168.10.5              54863          6  7/7/2017 3:30

    Flow Duration   Total Fwd Packets   Total Backward Packets  ...  \
0               3                   2                        0  ...
1             109                   1                        1  ...
2              52                   1                        1  ...
3              34                   1                        1  ...
4               3                   2                        0  ...

    min_seg_size_forward  Active Mean   Active Std   Active Max   Active Min  \
0                     20          0.0          0.0            0            0
1                     20          0.0          0.0            0            0
2                     20          0.0          0.0            0            0
3                     20          0.0          0.0            0            0
4                     20          0.0          0.0            0            0

   Idle Mean   Idle Std   Idle Max   Idle Min   Label
0        0.0        0.0          0          0  BENIGN
1        0.0        0.0          0          0  BENIGN
2        0.0        0.0          0          0  BENIGN
3        0.0        0.0          0          0  BENIGN
4        0.0        0.0          0          0  BENIGN

[5 rows x 85 columns]
(225745, 85)
Index(['Flow ID', ' Source IP', ' Source Port', ' Destination IP',
       ' Destination Port', ' Protocol', ' Timestamp', ' Flow Duration',
       ' Total Fwd Packets', ' Total Backward Packets',
       'Total Length of Fwd Packets', ' Total Length of Bwd Packets',
       ' Fwd Packet Length Max', ' Fwd Packet Length Min',
       ' Fwd Packet Length Mean', ' Fwd Packet Length Std',
       'Bwd Packet Length Max', ' Bwd Packet Length Min',
       ' Bwd Packet Length Mean', ' Bwd Packet Length Std', 'Flow Bytes/s',
       ' Flow Packets/s', ' Flow IAT Mean', ' Flow IAT Std', ' Flow IAT Max',
       ' Flow IAT Min', 'Fwd IAT Total', ' Fwd IAT Mean', ' Fwd IAT Std',
       ' Fwd IAT Max', ' Fwd IAT Min', 'Bwd IAT Total', ' Bwd IAT Mean',
       ' Bwd IAT Std', ' Bwd IAT Max', ' Bwd IAT Min', 'Fwd PSH Flags',
       ' Bwd PSH Flags', ' Fwd URG Flags', ' Bwd URG Flags',
       ' Fwd Header Length', ' Bwd Header Length', 'Fwd Packets/s',
       ' Bwd Packets/s', ' Min Packet Length', ' Max Packet Length',
       ' Packet Length Mean', ' Packet Length Std', ' Packet Length Variance',
       'FIN Flag Count', ' SYN Flag Count', ' RST Flag Count',
       ' PSH Flag Count', ' ACK Flag Count', ' URG Flag Count',
       ' CWE Flag Count', ' ECE Flag Count', ' Down/Up Ratio',
       ' Average Packet Size', ' Avg Fwd Segment Size',
       ' Avg Bwd Segment Size', ' Fwd Header Length.1', 'Fwd Avg Bytes/Bulk',
       ' Fwd Avg Packets/Bulk', ' Fwd Avg Bulk Rate', ' Bwd Avg Bytes/Bulk',
       ' Bwd Avg Packets/Bulk', 'Bwd Avg Bulk Rate', 'Subflow Fwd Packets',
       ' Subflow Fwd Bytes', ' Subflow Bwd Packets', ' Subflow Bwd Bytes',
       'Init_Win_bytes_forward', ' Init_Win_bytes_backward',
       ' act_data_pkt_fwd', ' min_seg_size_forward', 'Active Mean',
       ' Active Std', ' Active Max', ' Active Min', 'Idle Mean', ' Idle Std',
       ' Idle Max', ' Idle Min', ' Label'],
      dtype='str')

In [17]:
import pandas as pd

df = pd.read_csv("../dataset/Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv")

In [18]:
df.shape

(225743, 85)

In [3]:
df.columns.tolist()

['Flow ID',
 ' Source IP',
 ' Source Port',
 ' Destination IP',
 ' Destination Port',
 ' Protocol',
 ' Timestamp',
 ' Flow Duration',
 ' Total Fwd Packets',
 ' Total Backward Packets',
 'Total Length of Fwd Packets',
 ' Total Length of Bwd Packets',
 ' Fwd Packet Length Max',
 ' Fwd Packet Length Min',
 ' Fwd Packet Length Mean',
 ' Fwd Packet Length Std',
 'Bwd Packet Length Max',
 ' Bwd Packet Length Min',
 ' Bwd Packet Length Mean',
 ' Bwd Packet Length Std',
 'Flow Bytes/s',
 ' Flow Packets/s',
 ' Flow IAT Mean',
 ' Flow IAT Std',
 ' Flow IAT Max',
 ' Flow IAT Min',
 'Fwd IAT Total',
 ' Fwd IAT Mean',
 ' Fwd IAT Std',
 ' Fwd IAT Max',
 ' Fwd IAT Min',
 'Bwd IAT Total',
 ' Bwd IAT Mean',
 ' Bwd IAT Std',
 ' Bwd IAT Max',
 ' Bwd IAT Min',
 'Fwd PSH Flags',
 ' Bwd PSH Flags',
 ' Fwd URG Flags',
 ' Bwd URG Flags',
 ' Fwd Header Length',
 ' Bwd Header Length',
 'Fwd Packets/s',
 ' Bwd Packets/s',
 ' Min Packet Length',
 ' Max Packet Length',
 ' Packet Length Mean',
 ' Packet Length Std',
 ' Packet Length Variance',
 'FIN Flag Count',
 ' SYN Flag Count',
 ' RST Flag Count',
 ' PSH Flag Count',
 ' ACK Flag Count',
 ' URG Flag Count',
 ' CWE Flag Count',
 ' ECE Flag Count',
 ' Down/Up Ratio',
 ' Average Packet Size',
 ' Avg Fwd Segment Size',
 ' Avg Bwd Segment Size',
 ' Fwd Header Length.1',
 'Fwd Avg Bytes/Bulk',
 ' Fwd Avg Packets/Bulk',
 ' Fwd Avg Bulk Rate',
 ' Bwd Avg Bytes/Bulk',
 ' Bwd Avg Packets/Bulk',
 'Bwd Avg Bulk Rate',
 'Subflow Fwd Packets',
 ' Subflow Fwd Bytes',
 ' Subflow Bwd Packets',
 ' Subflow Bwd Bytes',
 'Init_Win_bytes_forward',
 ' Init_Win_bytes_backward',
 ' act_data_pkt_fwd',
 ' min_seg_size_forward',
 'Active Mean',
 ' Active Std',
 ' Active Max',
 ' Active Min',
 'Idle Mean',
 ' Idle Std',
 ' Idle Max',
 ' Idle Min',
 ' Label']

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 225743 entries, 0 to 225742
Data columns (total 85 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Flow ID                       225743 non-null  str
 1    Source IP                    225743 non-null  str
 2    Source Port                  225743 non-null  int64
 3    Destination IP               225743 non-null  str
 4    Destination Port             225743 non-null  int64
 5    Protocol                     225743 non-null  int64
 6    Timestamp                    225743 non-null  str
 7    Flow Duration                225743 non-null  int64
 8    Total Fwd Packets            225743 non-null  int64
 9    Total Backward Packets       225743 non-null  int64
 10  Total Length of Fwd Packets   225743 non-null  int64
 11   Total Length of Bwd Packets  225743 non-null  int64
 12   Fwd Packet Length Max        225743 non-null  int64
 13   Fwd Packet Length Min        225743 non-null  int64
 14   Fwd Packet Length Mean       225743 non-null  float64
 15   Fwd Packet Length Std        225743 non-null  float64
 16  Bwd Packet Length Max         225743 non-null  int64
 17   Bwd Packet Length Min        225743 non-null  int64
 18   Bwd Packet Length Mean       225743 non-null  float64
 19   Bwd Packet Length Std        225743 non-null  float64
 20  Flow Bytes/s                  225739 non-null  float64
 21   Flow Packets/s               225743 non-null  float64
 22   Flow IAT Mean                225743 non-null  float64
 23   Flow IAT Std                 225743 non-null  float64
 24   Flow IAT Max                 225743 non-null  int64
 25   Flow IAT Min                 225743 non-null  int64
 26  Fwd IAT Total                 225743 non-null  int64
 27   Fwd IAT Mean                 225743 non-null  float64
 28   Fwd IAT Std                  225743 non-null  float64
 29   Fwd IAT Max                  225743 non-null  int64
 30   Fwd IAT Min                  225743 non-null  int64
 31  Bwd IAT Total                 225743 non-null  int64
 32   Bwd IAT Mean                 225743 non-null  float64
 33   Bwd IAT Std                  225743 non-null  float64
 34   Bwd IAT Max                  225743 non-null  int64
 35   Bwd IAT Min                  225743 non-null  int64
 36  Fwd PSH Flags                 225743 non-null  int64
 37   Bwd PSH Flags                225743 non-null  int64
 38   Fwd URG Flags                225743 non-null  int64
 39   Bwd URG Flags                225743 non-null  int64
 40   Fwd Header Length            225743 non-null  int64
 41   Bwd Header Length            225743 non-null  int64
 42  Fwd Packets/s                 225743 non-null  float64
 43   Bwd Packets/s                225743 non-null  float64
 44   Min Packet Length            225743 non-null  int64
 45   Max Packet Length            225743 non-null  int64
 46   Packet Length Mean           225743 non-null  float64
 47   Packet Length Std            225743 non-null  float64
 48   Packet Length Variance       225743 non-null  float64
 49  FIN Flag Count                225743 non-null  int64
 50   SYN Flag Count               225743 non-null  int64
 51   RST Flag Count               225743 non-null  int64
 52   PSH Flag Count               225743 non-null  int64
 53   ACK Flag Count               225743 non-null  int64
 54   URG Flag Count               225743 non-null  int64
 55   CWE Flag Count               225743 non-null  int64
 56   ECE Flag Count               225743 non-null  int64
 57   Down/Up Ratio                225743 non-null  int64
 58   Average Packet Size          225743 non-null  float64
 59   Avg Fwd Segment Size         225743 non-null  float64
 60   Avg Bwd Segment Size         225743 non-null  float64
 61   Fwd Header Length.1          225743 non-null  int64
 62  Fwd Avg Bytes/Bulk            225743 non-null  int64
 63   Fwd Avg Packets/Bulk         225743 non-null  int64
 64   Fwd Avg Bulk Rate            225743 non-null  int64
 65   Bwd Avg Bytes/Bulk           225743 non-null  int64
 66   Bwd Avg Packets/Bulk         225743 non-null  int64
 67  Bwd Avg Bulk Rate             225743 non-null  int64
 68  Subflow Fwd Packets           225743 non-null  int64
 69   Subflow Fwd Bytes            225743 non-null  int64
 70   Subflow Bwd Packets          225743 non-null  int64
 71   Subflow Bwd Bytes            225743 non-null  int64
 72  Init_Win_bytes_forward        225743 non-null  int64
 73   Init_Win_bytes_backward      225743 non-null  int64
 74   act_data_pkt_fwd             225743 non-null  int64
 75   min_seg_size_forward         225743 non-null  int64
 76  Active Mean                   225743 non-null  float64
 77   Active Std                   225743 non-null  float64
 78   Active Max                   225743 non-null  int64
 79   Active Min                   225743 non-null  int64
 80  Idle Mean                     225743 non-null  float64
 81   Idle Std                     225743 non-null  float64
 82   Idle Max                     225743 non-null  int64
 83   Idle Min                     225743 non-null  int64
 84   Label                        225743 non-null  str
dtypes: float64(24), int64(56), str(5)
memory usage: 146.4 MB

In [20]:
df[" Label"].value_counts()

 Label
DDoS      128027
BENIGN     97716
Name: count, dtype: int64

In [6]:
print(df.columns.tolist())

['Flow ID', ' Source IP', ' Source Port', ' Destination IP', ' Destination Port', ' Protocol', ' Timestamp', ' Flow Duration', ' Total Fwd Packets', ' Total Backward Packets', 'Total Length of Fwd Packets', ' Total Length of Bwd Packets', ' Fwd Packet Length Max', ' Fwd Packet Length Min', ' Fwd Packet Length Mean', ' Fwd Packet Length Std', 'Bwd Packet Length Max', ' Bwd Packet Length Min', ' Bwd Packet Length Mean', ' Bwd Packet Length Std', 'Flow Bytes/s', ' Flow Packets/s', ' Flow IAT Mean', ' Flow IAT Std', ' Flow IAT Max', ' Flow IAT Min', 'Fwd IAT Total', ' Fwd IAT Mean', ' Fwd IAT Std', ' Fwd IAT Max', ' Fwd IAT Min', 'Bwd IAT Total', ' Bwd IAT Mean', ' Bwd IAT Std', ' Bwd IAT Max', ' Bwd IAT Min', 'Fwd PSH Flags', ' Bwd PSH Flags', ' Fwd URG Flags', ' Bwd URG Flags', ' Fwd Header Length', ' Bwd Header Length', 'Fwd Packets/s', ' Bwd Packets/s', ' Min Packet Length', ' Max Packet Length', ' Packet Length Mean', ' Packet Length Std', ' Packet Length Variance', 'FIN Flag Count', ' SYN Flag Count', ' RST Flag Count', ' PSH Flag Count', ' ACK Flag Count', ' URG Flag Count', ' CWE Flag Count', ' ECE Flag Count', ' Down/Up Ratio', ' Average Packet Size', ' Avg Fwd Segment Size', ' Avg Bwd Segment Size', ' Fwd Header Length.1', 'Fwd Avg Bytes/Bulk', ' Fwd Avg Packets/Bulk', ' Fwd Avg Bulk Rate', ' Bwd Avg Bytes/Bulk', ' Bwd Avg Packets/Bulk', 'Bwd Avg Bulk Rate', 'Subflow Fwd Packets', ' Subflow Fwd Bytes', ' Subflow Bwd Packets', ' Subflow Bwd Bytes', 'Init_Win_bytes_forward', ' Init_Win_bytes_backward', ' act_data_pkt_fwd', ' min_seg_size_forward', 'Active Mean', ' Active Std', ' Active Max', ' Active Min', 'Idle Mean', ' Idle Std', ' Idle Max', ' Idle Min', ' Label']

In [21]:
df.describe()

A:\ML_Intrusion_Detection\.venv\Lib\site-packages\pandas\core\nanops.py:1028: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)
A:\ML_Intrusion_Detection\.venv\Lib\site-packages\pandas\core\nanops.py:1028: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)

,Source Port,Destination Port,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,...,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min
count,225743.000000,225743.000000,225743.000000,2.257430e+05,225743.000000,225743.000000,225743.000000,2.257430e+05,225743.000000,225743.000000,...,225743.000000,225743.000000,2.257430e+05,2.257430e+05,2.257430e+05,2.257430e+05,2.257430e+05,2.257430e+05,2.257430e+05,2.257430e+05
mean,38257.597502,8879.695813,7.600302,1.624179e+07,4.874951,4.572806,939.471616,5.960530e+03,538.540411,27.882415,...,3.311527,21.482766,1.848277e+05,1.293447e+04,2.080867e+05,1.776217e+05,1.032223e+07,3.611975e+06,1.287824e+07,7.755424e+06
std,23057.285091,19754.718247,3.881601,3.152448e+07,15.422938,21.755450,3249.416690,3.921851e+04,1864.136575,163.324869,...,12.270068,4.166815,7.979284e+05,2.102746e+05,9.002388e+05,7.842635e+05,2.185310e+07,1.275695e+07,2.692136e+07,1.983117e+07
min,0.000000,0.000000,0.000000,0.000000e+00,1.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,...,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,18990.000000,80.000000,6.000000,7.118200e+04,2.000000,1.000000,26.000000,0.000000e+00,6.000000,0.000000,...,1.000000,20.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,49799.000000,80.000000,6.000000,1.452338e+06,3.000000,4.000000,30.000000,1.640000e+02,20.000000,0.000000,...,2.000000,20.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,58296.000000,80.000000,6.000000,8.805241e+06,5.000000,5.000000,63.000000,1.160100e+04,34.000000,6.000000,...,4.000000,20.000000,1.878000e+03,0.000000e+00,1.878000e+03,1.862000e+03,8.239740e+06,0.000000e+00,8.253854e+06,7.422860e+06
max,65534.000000,65532.000000,17.000000,1.199999e+08,1932.000000,2942.000000,183012.000000,5.172346e+06,11680.000000,1472.000000,...,1931.000000,52.000000,1.000000e+08,3.950000e+07,1.000000e+08,1.000000e+08,1.200000e+08,6.530000e+07,1.200000e+08,1.200000e+08

In [22]:
(df[" Flow Duration"] < 0).sum()

np.int64(0)

In [23]:
df[df[" Flow Duration"] < 0]

Empty DataFrame
Columns: [Flow ID,  Source IP,  Source Port,  Destination IP,  Destination Port,  Protocol,  Timestamp,  Flow Duration,  Total Fwd Packets,  Total Backward Packets, Total Length of Fwd Packets,  Total Length of Bwd Packets,  Fwd Packet Length Max,  Fwd Packet Length Min,  Fwd Packet Length Mean,  Fwd Packet Length Std, Bwd Packet Length Max,  Bwd Packet Length Min,  Bwd Packet Length Mean,  Bwd Packet Length Std, Flow Bytes/s,  Flow Packets/s,  Flow IAT Mean,  Flow IAT Std,  Flow IAT Max,  Flow IAT Min, Fwd IAT Total,  Fwd IAT Mean,  Fwd IAT Std,  Fwd IAT Max,  Fwd IAT Min, Bwd IAT Total,  Bwd IAT Mean,  Bwd IAT Std,  Bwd IAT Max,  Bwd IAT Min, Fwd PSH Flags,  Bwd PSH Flags,  Fwd URG Flags,  Bwd URG Flags,  Fwd Header Length,  Bwd Header Length, Fwd Packets/s,  Bwd Packets/s,  Min Packet Length,  Max Packet Length,  Packet Length Mean,  Packet Length Std,  Packet Length Variance, FIN Flag Count,  SYN Flag Count,  RST Flag Count,  PSH Flag Count,  ACK Flag Count,  URG Flag Count,  CWE Flag Count,  ECE Flag Count,  Down/Up Ratio,  Average Packet Size,  Avg Fwd Segment Size,  Avg Bwd Segment Size,  Fwd Header Length.1, Fwd Avg Bytes/Bulk,  Fwd Avg Packets/Bulk,  Fwd Avg Bulk Rate,  Bwd Avg Bytes/Bulk,  Bwd Avg Packets/Bulk, Bwd Avg Bulk Rate, Subflow Fwd Packets,  Subflow Fwd Bytes,  Subflow Bwd Packets,  Subflow Bwd Bytes, Init_Win_bytes_forward,  Init_Win_bytes_backward,  act_data_pkt_fwd,  min_seg_size_forward, Active Mean,  Active Std,  Active Max,  Active Min, Idle Mean,  Idle Std,  Idle Max,  Idle Min,  Label]
Index: []

[0 rows x 85 columns]

In [13]:
df[" Flow Duration"].min()

np.int64(-1)

In [24]:
df[df[" Flow Duration"]<0]

Empty DataFrame
Columns: [Flow ID,  Source IP,  Source Port,  Destination IP,  Destination Port,  Protocol,  Timestamp,  Flow Duration,  Total Fwd Packets,  Total Backward Packets, Total Length of Fwd Packets,  Total Length of Bwd Packets,  Fwd Packet Length Max,  Fwd Packet Length Min,  Fwd Packet Length Mean,  Fwd Packet Length Std, Bwd Packet Length Max,  Bwd Packet Length Min,  Bwd Packet Length Mean,  Bwd Packet Length Std, Flow Bytes/s,  Flow Packets/s,  Flow IAT Mean,  Flow IAT Std,  Flow IAT Max,  Flow IAT Min, Fwd IAT Total,  Fwd IAT Mean,  Fwd IAT Std,  Fwd IAT Max,  Fwd IAT Min, Bwd IAT Total,  Bwd IAT Mean,  Bwd IAT Std,  Bwd IAT Max,  Bwd IAT Min, Fwd PSH Flags,  Bwd PSH Flags,  Fwd URG Flags,  Bwd URG Flags,  Fwd Header Length,  Bwd Header Length, Fwd Packets/s,  Bwd Packets/s,  Min Packet Length,  Max Packet Length,  Packet Length Mean,  Packet Length Std,  Packet Length Variance, FIN Flag Count,  SYN Flag Count,  RST Flag Count,  PSH Flag Count,  ACK Flag Count,  URG Flag Count,  CWE Flag Count,  ECE Flag Count,  Down/Up Ratio,  Average Packet Size,  Avg Fwd Segment Size,  Avg Bwd Segment Size,  Fwd Header Length.1, Fwd Avg Bytes/Bulk,  Fwd Avg Packets/Bulk,  Fwd Avg Bulk Rate,  Bwd Avg Bytes/Bulk,  Bwd Avg Packets/Bulk, Bwd Avg Bulk Rate, Subflow Fwd Packets,  Subflow Fwd Bytes,  Subflow Bwd Packets,  Subflow Bwd Bytes, Init_Win_bytes_forward,  Init_Win_bytes_backward,  act_data_pkt_fwd,  min_seg_size_forward, Active Mean,  Active Std,  Active Max,  Active Min, Idle Mean,  Idle Std,  Idle Max,  Idle Min,  Label]
Index: []

[0 rows x 85 columns]

In [25]:
df[df[" Flow Duration"] < 0]

Empty DataFrame
Columns: [Flow ID,  Source IP,  Source Port,  Destination IP,  Destination Port,  Protocol,  Timestamp,  Flow Duration,  Total Fwd Packets,  Total Backward Packets, Total Length of Fwd Packets,  Total Length of Bwd Packets,  Fwd Packet Length Max,  Fwd Packet Length Min,  Fwd Packet Length Mean,  Fwd Packet Length Std, Bwd Packet Length Max,  Bwd Packet Length Min,  Bwd Packet Length Mean,  Bwd Packet Length Std, Flow Bytes/s,  Flow Packets/s,  Flow IAT Mean,  Flow IAT Std,  Flow IAT Max,  Flow IAT Min, Fwd IAT Total,  Fwd IAT Mean,  Fwd IAT Std,  Fwd IAT Max,  Fwd IAT Min, Bwd IAT Total,  Bwd IAT Mean,  Bwd IAT Std,  Bwd IAT Max,  Bwd IAT Min, Fwd PSH Flags,  Bwd PSH Flags,  Fwd URG Flags,  Bwd URG Flags,  Fwd Header Length,  Bwd Header Length, Fwd Packets/s,  Bwd Packets/s,  Min Packet Length,  Max Packet Length,  Packet Length Mean,  Packet Length Std,  Packet Length Variance, FIN Flag Count,  SYN Flag Count,  RST Flag Count,  PSH Flag Count,  ACK Flag Count,  URG Flag Count,  CWE Flag Count,  ECE Flag Count,  Down/Up Ratio,  Average Packet Size,  Avg Fwd Segment Size,  Avg Bwd Segment Size,  Fwd Header Length.1, Fwd Avg Bytes/Bulk,  Fwd Avg Packets/Bulk,  Fwd Avg Bulk Rate,  Bwd Avg Bytes/Bulk,  Bwd Avg Packets/Bulk, Bwd Avg Bulk Rate, Subflow Fwd Packets,  Subflow Fwd Bytes,  Subflow Bwd Packets,  Subflow Bwd Bytes, Init_Win_bytes_forward,  Init_Win_bytes_backward,  act_data_pkt_fwd,  min_seg_size_forward, Active Mean,  Active Std,  Active Max,  Active Min, Idle Mean,  Idle Std,  Idle Max,  Idle Min,  Label]
Index: []

[0 rows x 85 columns]

In [26]:
df.isnull().sum().sum()

np.int64(4)

In [27]:
df.isnull().sum()[df.isnull().sum() > 0]

Flow Bytes/s    4
dtype: int64