In [1]:
import pandas as pd

df = pd.read_csv("../dataset/Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv")

In [2]:
df.shape

(225743, 85)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 225743 entries, 0 to 225742
Data columns (total 85 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Flow ID                      225743 non-null  str
 1   Source IP                    225743 non-null  str
 2   Source Port                  225743 non-null  int64
 3   Destination IP               225743 non-null  str
 4   Destination Port             225743 non-null  int64
 5   Protocol                     225743 non-null  int64
 6   Timestamp                    225743 non-null  str
 7   Flow Duration                225743 non-null  int64
 8   Total Fwd Packets            225743 non-null  int64
 9   Total Backward Packets       225743 non-null  int64
 10  Total Length of Fwd Packets  225743 non-null  int64
 11  Total Length of Bwd Packets  225743 non-null  int64
 12  Fwd Packet Length Max        225743 non-null  int64
 13  Fwd Packet Length Min        225743 non-null  int64
 14  Fwd Packet Length Mean       225743 non-null  float64
 15  Fwd Packet Length Std        225743 non-null  float64
 16  Bwd Packet Length Max        225743 non-null  int64
 17  Bwd Packet Length Min        225743 non-null  int64
 18  Bwd Packet Length Mean       225743 non-null  float64
 19  Bwd Packet Length Std        225743 non-null  float64
 20  Flow Bytes/s                 225739 non-null  float64
 21  Flow Packets/s               225743 non-null  float64
 22  Flow IAT Mean                225743 non-null  float64
 23  Flow IAT Std                 225743 non-null  float64
 24  Flow IAT Max                 225743 non-null  int64
 25  Flow IAT Min                 225743 non-null  int64
 26  Fwd IAT Total                225743 non-null  int64
 27  Fwd IAT Mean                 225743 non-null  float64
 28  Fwd IAT Std                  225743 non-null  float64
 29  Fwd IAT Max                  225743 non-null  int64
 30  Fwd IAT Min                  225743 non-null  int64
 31  Bwd IAT Total                225743 non-null  int64
 32  Bwd IAT Mean                 225743 non-null  float64
 33  Bwd IAT Std                  225743 non-null  float64
 34  Bwd IAT Max                  225743 non-null  int64
 35  Bwd IAT Min                  225743 non-null  int64
 36  Fwd PSH Flags                225743 non-null  int64
 37  Bwd PSH Flags                225743 non-null  int64
 38  Fwd URG Flags                225743 non-null  int64
 39  Bwd URG Flags                225743 non-null  int64
 40  Fwd Header Length            225743 non-null  int64
 41  Bwd Header Length            225743 non-null  int64
 42  Fwd Packets/s                225743 non-null  float64
 43  Bwd Packets/s                225743 non-null  float64
 44  Min Packet Length            225743 non-null  int64
 45  Max Packet Length            225743 non-null  int64
 46  Packet Length Mean           225743 non-null  float64
 47  Packet Length Std            225743 non-null  float64
 48  Packet Length Variance       225743 non-null  float64
 49  FIN Flag Count               225743 non-null  int64
 50  SYN Flag Count               225743 non-null  int64
 51  RST Flag Count               225743 non-null  int64
 52  PSH Flag Count               225743 non-null  int64
 53  ACK Flag Count               225743 non-null  int64
 54   URG Flag Count              225743 non-null  int64
 55  CWE Flag Count               225743 non-null  int64
 56  ECE Flag Count               225743 non-null  int64
 57  Down/Up Ratio                225743 non-null  int64
 58   Average Packet Size         225743 non-null  float64
 59  Avg Fwd Segment Size         225743 non-null  float64
 60  Avg Bwd Segment Size         225743 non-null  float64
 61  Fwd Header Length.1          225743 non-null  int64
 62  Fwd Avg Bytes/Bulk           225743 non-null  int64
 63  Fwd Avg Packets/Bulk         225743 non-null  int64
 64  Fwd Avg Bulk Rate            225743 non-null  int64
 65  Bwd Avg Bytes/Bulk           225743 non-null  int64
 66  Bwd Avg Packets/Bulk         225743 non-null  int64
 67  Bwd Avg Bulk Rate            225743 non-null  int64
 68  Subflow Fwd Packets          225743 non-null  int64
 69  Subflow Fwd Bytes            225743 non-null  int64
 70  Subflow Bwd Packets          225743 non-null  int64
 71  Subflow Bwd Bytes            225743 non-null  int64
 72  Init_Win_bytes_forward       225743 non-null  int64
 73  Init_Win_bytes_backward      225743 non-null  int64
 74  act_data_pkt_fwd             225743 non-null  int64
 75  min_seg_size_forward         225743 non-null  int64
 76  Active Mean                  225743 non-null  float64
 77  Active Std                   225743 non-null  float64
 78  Active Max                   225743 non-null  int64
 79  Active Min                   225743 non-null  int64
 80  Idle Mean                    225743 non-null  float64
 81  Idle Std                     225743 non-null  float64
 82  Idle Max                     225743 non-null  int64
 83  Idle Min                     225743 non-null  int64
 84  Label                        225743 non-null  str
dtypes: float64(24), int64(56), str(5)
memory usage: 146.4 MB

In [4]:
df.columns = df.columns.str.strip()

In [5]:
df.isnull().sum()[df.isnull().sum() > 0]

Flow Bytes/s    4
dtype: int64

In [6]:
df[df["Flow Bytes/s"].isnull()]

,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,Total Backward Packets,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
6796,192.168.10.16-198.54.12.145-36812-80-6,198.54.12.145,80,192.168.10.16,36812,6,07-07-2017 03:35,0,2,0,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
14739,192.168.10.25-192.168.10.50-53581-37575-6,192.168.10.50,37575,192.168.10.25,53581,6,07-07-2017 03:46,0,1,1,...,44,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
15047,192.168.10.17-1.1.70.73-48283-80-6,192.168.10.17,48283,1.1.70.73,80,6,07-07-2017 03:48,0,2,0,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
209727,192.168.10.17-192.168.10.50-39026-18467-6,192.168.10.17,39026,192.168.10.50,18467,6,07-07-2017 04:34,0,2,0,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN

In [7]:
df.duplicated().sum()

np.int64(2)

In [8]:
(df["Flow Duration"] < 0).sum()

np.int64(0)

In [10]:
constant_columns = [
    col
    for col in df.columns
    if df[col].nunique() == 1
]

In [12]:
df = df.dropna()

In [13]:
df.isnull().sum()[df.isnull().sum() > 0]

Series([], dtype: int64)

In [14]:
df = df.dropna()

In [15]:
df = df.drop_duplicates()

In [16]:
print(df.shape)

(225737, 85)

In [18]:
identifier_columns = [
    "Flow ID",
    "Source IP",
    "Destination IP",
    "Timestamp"
]

df = df.drop(columns=identifier_columns)

KeyError: "['Flow ID', 'Source IP', 'Destination IP', 'Timestamp'] not found in axis"

In [19]:
for col in df.columns:
    print(repr(col))

'Source Port'
'Destination Port'
'Protocol'
'Flow Duration'
'Total Fwd Packets'
'Total Backward Packets'
'Total Length of Fwd Packets'
'Total Length of Bwd Packets'
'Fwd Packet Length Max'
'Fwd Packet Length Min'
'Fwd Packet Length Mean'
'Fwd Packet Length Std'
'Bwd Packet Length Max'
'Bwd Packet Length Min'
'Bwd Packet Length Mean'
'Bwd Packet Length Std'
'Flow Bytes/s'
'Flow Packets/s'
'Flow IAT Mean'
'Flow IAT Std'
'Flow IAT Max'
'Flow IAT Min'
'Fwd IAT Total'
'Fwd IAT Mean'
'Fwd IAT Std'
'Fwd IAT Max'
'Fwd IAT Min'
'Bwd IAT Total'
'Bwd IAT Mean'
'Bwd IAT Std'
'Bwd IAT Max'
'Bwd IAT Min'
'Fwd PSH Flags'
'Bwd PSH Flags'
'Fwd URG Flags'
'Bwd URG Flags'
'Fwd Header Length'
'Bwd Header Length'
'Fwd Packets/s'
'Bwd Packets/s'
'Min Packet Length'
'Max Packet Length'
'Packet Length Mean'
'Packet Length Std'
'Packet Length Variance'
'FIN Flag Count'
'SYN Flag Count'
'RST Flag Count'
'PSH Flag Count'
'ACK Flag Count'
'URG Flag Count'
'CWE Flag Count'
'ECE Flag Count'
'Down/Up Ratio'
'Average Packet Size'
'Avg Fwd Segment Size'
'Avg Bwd Segment Size'
'Fwd Header Length.1'
'Fwd Avg Bytes/Bulk'
'Fwd Avg Packets/Bulk'
'Fwd Avg Bulk Rate'
'Bwd Avg Bytes/Bulk'
'Bwd Avg Packets/Bulk'
'Bwd Avg Bulk Rate'
'Subflow Fwd Packets'
'Subflow Fwd Bytes'
'Subflow Bwd Packets'
'Subflow Bwd Bytes'
'Init_Win_bytes_forward'
'Init_Win_bytes_backward'
'act_data_pkt_fwd'
'min_seg_size_forward'
'Active Mean'
'Active Std'
'Active Max'
'Active Min'
'Idle Mean'
'Idle Std'
'Idle Max'
'Idle Min'
'Label'

In [20]:
X = df.drop("Label", axis=1)

y = df["Label"]

In [21]:
print(X.shape)

print(y.shape)

(225737, 80)
(225737,)

In [22]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

y = encoder.fit_transform(y)

In [23]:
print(set(y))

{np.int64(0), np.int64(1)}

In [24]:
print(encoder.classes_)

['BENIGN' 'DDoS']

In [25]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [26]:
print(X_train.shape)
print(X_test.shape)

print(y_train.shape)
print(y_test.shape)

(180589, 80)
(45148, 80)
(180589,)
(45148,)

In [27]:
from sklearn.linear_model import LogisticRegression

In [29]:
model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

In [30]:
model.fit(X_train, y_train)

ValueError: Input X contains infinity or a value too large for dtype('float64').

In [31]:
import numpy as np

np.isinf(X).sum().sum()

np.int64(60)

In [32]:
inf_columns = X.columns[np.isinf(X).any()]

print(inf_columns)

Index(['Flow Bytes/s', 'Flow Packets/s'], dtype='str')

In [33]:
import numpy as np

df.replace([np.inf, -np.inf], np.nan, inplace=True)

,Source Port,Destination Port,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,443,54865,6,3,2,0,12,0,6,6,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
1,80,55054,6,109,1,1,6,6,6,6,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2,80,55055,6,52,1,1,6,6,6,6,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
3,443,46236,6,34,1,1,6,6,6,6,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
4,443,54863,6,3,2,0,12,0,6,6,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225738,80,61374,6,61,1,1,6,6,6,6,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
225739,80,61378,6,72,1,1,6,6,6,6,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
225740,80,61375,6,75,1,1,6,6,6,6,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
225741,80,61323,6,48,2,0,12,0,6,6,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
225742,80,61326,6,68,1,1,6,6,6,6,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN

In [34]:
df.dropna(inplace=True)

In [35]:
np.isinf(df).sum().sum()

TypeError: ufunc 'isinf' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [36]:
import numpy as np

df.replace([np.inf, -np.inf], np.nan, inplace=True)
df.dropna(inplace=True)

In [37]:
X = df.drop(columns="Label")
y = df["Label"]

In [38]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
y = encoder.fit_transform(y)

In [39]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [40]:
from sklearn.linear_model import LogisticRegression

In [41]:
model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

In [42]:
model.fit(X_train, y_train)

C:\Users\ayush\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000, random_state=42)

In [43]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [44]:
model = LogisticRegression(
    random_state=42,
    max_iter=1000
)

In [45]:
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=42)

In [46]:
y_pred = model.predict(X_test)

In [47]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.9985600992423906

In [48]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

[[19494    43]
 [   22 25583]]

In [49]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     19537
           1       1.00      1.00      1.00     25605

    accuracy                           1.00     45142
   macro avg       1.00      1.00      1.00     45142
weighted avg       1.00      1.00      1.00     45142

In [50]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred, digits=6))

              precision    recall  f1-score   support

           0   0.998873  0.997799  0.998336     19537
           1   0.998322  0.999141  0.998731     25605

    accuracy                       0.998560     45142
   macro avg   0.998597  0.998470  0.998533     45142
weighted avg   0.998560  0.998560  0.998560     45142